#ifndef ERRORS_H
#define ERRORS_H

#define ALLOCATION_MEMORY_ERROR 1
#define REALLOCATION_MEMORY_ERROR 2
#define PTR_NULL 3
#define OPENING_FILE_ERROR -1
#define VALUE_ERROR -2
#define INCORRECT_DATA_FORMAT -3
#define INCORRECT_KEY_VALUE_FORMAT -4

#endif